# Generated by Django 3.1.3 on 2020-11-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_site', models.TextField(unique=True)),
                ('block', models.CharField(max_length=250)),
            ],
        ),
    ]
