# Generated by Django 3.1.3 on 2020-11-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxApp', '0002_crawl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='web_site',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
